### ISSUE TITLE
GET request for all restaurants

### ISSUE THREAD

**Issue by kristieelim** [robbdasailer/Techlabs_Group09_Backend#11]
According to the appointment schema, the restaurants are identified by an id. Is there any way to retrieve a list of restaurants together with their respective ids along with other information (eg: restaurant name, coordinates, store employee), perhaps through a GET request?

Also, how are the store employees assigned to their respective restaurants?

**Comment by robbdasailer** [comment]
Actually, the get request for the restaurants should work. Can you elaborate on what is not working?

**Comment by kristieelim** [comment]
The GET request is not documented in swagger.

**Comment by kristieelim** [comment]
It doesn't even need to be documented in swagger actually, but it needs to be documented in some way that I can understand it.

**Comment by robbdasailer** [comment]
Get request for restaurants included in swagger documentation
