### ISSUE TITLE
Change type to "ADMIN"

### ISSUE THREAD

**Issue by kristieelim** [robbdasailer/Techlabs_Group09_Backend#12]
Not an issue, but just a gentle reminder :)

Please manually change the type from "EMPLOYEE" to "ADMIN" for the user with the email admin@email.com in the database.

![WhatsApp Image 2023-03-30 at 5 01 26 PM](https://user-images.githubusercontent.com/33090459/229368010-9bb372be-e1e2-40cc-a151-641c9a1d315c.jpeg)

**Comment by robbdasailer** [comment]
Will proceed according to Marmik's suggestion
