### ISSUE TITLE
type: ['DRIVER', 'EMPLOYEE'] for user schema

### ISSUE THREAD

**Issue by kristieelim** [robbdasailer/Techlabs_Group09_Backend#2]
Based on the following image sent in the whatsapp group, user is an enum: ['DRIVER', 'EMPLOYEE'] in the user schema in db.js

![Image1](https://user-images.githubusercontent.com/33090459/226695966-28134afd-40fe-4a9a-abe2-6cba3f59f70d.jpeg)

Maybe the code hasn't been updated in github, but for example in line 38 of authController.js, the user enum ['DRIVER', 'RESTAURANT'] is still being used.

Please check that the user enum is the same for all files.

Also unfortunately, there is an error for the store employee registration. Driver registration works fine. Marmik suggested to check validation.

![Image2](https://user-images.githubusercontent.com/33090459/226697668-b8fd75cb-03c5-4823-ba68-880e40dfbcb5.jpeg)

Thank you!

**Comment by robbdasailer** [comment]
Changed the validation check for user types. Should work now.
