### ISSUE TITLE
GET request for /api/user results only null

### ISSUE THREAD

**Issue by kristieelim** [robbdasailer/Techlabs_Group09_Backend#3]
GET request for /api/user returns only null

![Screenshot (21)](https://user-images.githubusercontent.com/33090459/226699799-68282bee-2d28-4970-b0b7-519be27a08d5.png)

**Comment by robbdasailer** [comment]
Commented out some of the code:

return apiResponse.successResponseWithData(res, "Operation success", users);//.map(x => UserData(x)));

**Comment by robbdasailer** [comment]
Commented out some of the code:

return apiResponse.successResponseWithData(res, "Operation success", users);//.map(x => UserData(x)));

**Comment by kristieelim** [comment]
It works perfectly now, thank you!
