### ISSUE TITLE
POST /api/user doesn't work according to swagger documentation

### ISSUE THREAD

**Issue by kristieelim** [robbdasailer/Techlabs_Group09_Backend#4]
POST /api/user doesn't work according to swagger documentation. I get the following error message:

![Screenshot (23)](https://user-images.githubusercontent.com/33090459/227707119-303694c4-f3a7-4f12-918a-54fe3c18b4ba.png)

![Screenshot (25)](https://user-images.githubusercontent.com/33090459/227707105-db01f7bc-aa63-4832-8ce4-d061aa3a3606.png)

**Comment by robbdasailer** [comment]
Should work now

**Comment by kristieelim** [comment]
Thank you!
