### ISSUE TITLE
DELETE /api/user doesn't work according to the swagger documentation

### ISSUE THREAD

**Issue by kristieelim** [robbdasailer/Techlabs_Group09_Backend#5]
DELETE /api/user doesn't work according to the swagger documentation. The following is the error message:

![Screenshot (26)](https://user-images.githubusercontent.com/33090459/227708790-cd6f440f-57fa-4e69-b573-c9684c220b21.png)
![Screenshot (27)](https://user-images.githubusercontent.com/33090459/227708792-037007d7-fbe0-46d4-aee0-48fb445d821e.png)

**Comment by kristieelim** [comment]
This is the more current error message:

![Screenshot (49)](https://user-images.githubusercontent.com/33090459/228816014-ea401e9c-653b-46ef-bcd7-5809719e4b08.png)

![Screenshot (50)](https://user-images.githubusercontent.com/33090459/228816031-0ff7f40d-43c5-4f21-a582-eb38c782b364.png)

![Screenshot (48)](https://user-images.githubusercontent.com/33090459/228816148-4bbbf442-2942-4ded-bcb2-23c9ab2752b5.png)

**Comment by robbdasailer** [comment]
I could not resolve.
