### ISSUE TITLE
PUT /api/user doesn't work according to swagger documentation

### ISSUE THREAD

**Issue by kristieelim** [robbdasailer/Techlabs_Group09_Backend#6]
PUT /api/user doesn't work according to swagger documentation. Here is the error message:

![Screenshot (31)](https://user-images.githubusercontent.com/33090459/227709571-78b62259-42c1-44b7-b2b0-d3314304e866.png)
![Screenshot (32)](https://user-images.githubusercontent.com/33090459/227709573-2e678f61-e0cc-446b-b782-0aa57b2e8464.png)
![Screenshot (33)](https://user-images.githubusercontent.com/33090459/227709575-69cd68db-2cb7-4fef-b05e-f6226dd4e45b.png)

**Comment by marmik18** [comment]
Afaik, You need to pass authentication token to get a response

**Comment by robbdasailer** [comment]
I removed the auth function, but there is still something wrong in the toString part...

**Comment by kristieelim** [comment]
This is the current error message:

![Screenshot (46)](https://user-images.githubusercontent.com/33090459/228816499-e848e384-6514-4d83-86eb-472f7c28d1c4.png)

![Screenshot (47)](https://user-images.githubusercontent.com/33090459/228816510-0e94d6c5-e603-4c95-a890-d77ec2f8a89f.png)

![Screenshot (48)](https://user-images.githubusercontent.com/33090459/228816525-324e9591-d535-4a6a-a14d-4cc8721fdb1f.png)

**Comment by robbdasailer** [comment]
Probably same issue as in the delete request. I could not resolve.

**Comment by marmik18** [comment]
started working on this
