### ISSUE TITLE
Please enable cors for the netlify domain

### ISSUE THREAD

**Issue by kristieelim** [robbdasailer/Techlabs_Group09_Backend#7]
There is an issue based on cors in the netlify domain but not in localhost:3000. Please enable cors for the netlify domain: https://tafel-route.netlify.app/

**Comment by robbdasailer** [comment]
Added https://tafel-route.netlify.app to app.js file.

app.use(cors({
	origin: 'https://tafel-route.netlify.app'
}));

**Comment by kristieelim** [comment]
As enabling cors for two domains seems more complicated than our deadline allows, please enable cors only for localhost:3000. This is because we need it more than the netlify domain for now. 

app.use(cors({
origin: 'https://localhost:3000/'
}));
