### ISSUE TITLE
Adding an appointment is not available on swagger documentation

### ISSUE THREAD

**Issue by kristieelim** [robbdasailer/Techlabs_Group09_Backend#8]
There is no documentation on swagger about adding an appointment (post request for /apppointment/).

![Screenshot (38)](https://user-images.githubusercontent.com/33090459/228792494-b21b9bd1-3060-4e42-b533-739e55ee2326.png)

**Comment by robbdasailer** [comment]
It's available now. But appears to have issues.

**Comment by robbdasailer** [comment]
Issues fixed
