### ISSUE TITLE
GET /appointment/ doesn't work according to swagger

### ISSUE THREAD

**Issue by kristieelim** [robbdasailer/Techlabs_Group09_Backend#9]
GET /appointment/ doesn't work according to swagger. 

![Screenshot (41)](https://user-images.githubusercontent.com/33090459/228810649-4f7e5f77-3437-497f-9183-42301f5260e9.png)
![Screenshot (42)](https://user-images.githubusercontent.com/33090459/228810656-7b29d2f2-b2d7-4091-92f4-042d32785725.png)

**Comment by robbdasailer** [comment]
added /api/appointment
